-------------------------------------------------------------------------------
Test set: models.EndangeredAnimalTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 2.683 sec <<< FAILURE! - in models.EndangeredAnimalTest
all_returnsAllInstancesOfEndangeredAnimal_true(models.EndangeredAnimalTest)  Time elapsed: 0.514 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)

update_updatesAgeAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.582 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)

save_assignsIdAndSavesObjectToDatabase(models.EndangeredAnimalTest)  Time elapsed: 0.526 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)

find_returnsAnimalWithSameId_secondAnimal(models.EndangeredAnimalTest)  Time elapsed: 0.519 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)

update_updatesHealthAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.539 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.202.208.169", user "hhgxpccvuyngmn", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)

