<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="models.EndangeredTest" time="3.402" tests="7" errors="5" skipped="0" failures="1">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="java.vm.version" value="11.0.8+10"/>
    <property name="sun.boot.library.path" value="/home/kush/.sdkman/candidates/java/11.0.8.hs-adpt/lib"/>
    <property name="maven.multiModuleProjectDirectory" value="/home/kush/IdeaProjects/kush-range"/>
    <property name="java.vm.vendor" value="AdoptOpenJDK"/>
    <property name="java.vendor.url" value="https://adoptopenjdk.net/"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=":"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/kush/IdeaProjects/kush-range"/>
    <property name="java.vm.compressedOopsMode" value="32-bit"/>
    <property name="java.runtime.version" value="11.0.8+10"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="maven.conf" value="/usr/share/maven/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="55.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="5.0.0-32-generic"/>
    <property name="library.jansi.path" value="/usr/share/maven/lib/jansi-native"/>
    <property name="user.home" value="/home/kush"/>
    <property name="user.timezone" value="Africa/Nairobi"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="11"/>
    <property name="user.name" value="kush"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="11"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher heroku:deploy"/>
    <property name="java.home" value="/home/kush/.sdkman/candidates/java/11.0.8.hs-adpt"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="11.0.8"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="java.vendor" value="AdoptOpenJDK"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.version.date" value="2020-07-14"/>
    <property name="java.vendor.url.bug" value="https://github.com/AdoptOpenJDK/openjdk-support/issues"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="java.vendor.version" value="AdoptOpenJDK"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="endangeredAnimal_instantiatesCorrectly_true" classname="models.EndangeredTest" time="0"/>
  <testcase name="getHealth_returnsCorrectHealthAttribute_true" classname="models.EndangeredTest" time="0.001">
    <failure message="expected:&lt;[Healthy]&gt; but was:&lt;[Ill]&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: expected:<[Healthy]> but was:<[Ill]>
	at models.EndangeredTest.getHealth_returnsCorrectHealthAttribute_true(EndangeredTest.java:16)
]]></failure>
  </testcase>
  <testcase name="all_returnsAllInstancesOfEndangeredAnimal_true" classname="models.EndangeredTest" time="0.74">
    <error message="Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host &quot;154.153.170.206&quot;, user &quot;ccyhkvpngqxwcm&quot;, database &quot;d5j2hvlid2h80o&quot;, SSL off" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredTest.java:30)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredTest.java:30)
</error>
    <system-err><![CDATA[SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
]]></system-err>
  </testcase>
  <testcase name="update_updatesAgeAttribute_true" classname="models.EndangeredTest" time="0.615">
    <error message="Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host &quot;154.153.170.206&quot;, user &quot;ccyhkvpngqxwcm&quot;, database &quot;d5j2hvlid2h80o&quot;, SSL off" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.update_updatesAgeAttribute_true(EndangeredTest.java:57)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.update_updatesAgeAttribute_true(EndangeredTest.java:57)
</error>
  </testcase>
  <testcase name="save_assignsIdAndSavesObjectToDatabase" classname="models.EndangeredTest" time="0.744">
    <error message="Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host &quot;154.153.170.206&quot;, user &quot;ccyhkvpngqxwcm&quot;, database &quot;d5j2hvlid2h80o&quot;, SSL off" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.save_assignsIdAndSavesObjectToDatabase(EndangeredTest.java:22)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.save_assignsIdAndSavesObjectToDatabase(EndangeredTest.java:22)
</error>
  </testcase>
  <testcase name="find_returnsAnimalWithSameId_secondAnimal" classname="models.EndangeredTest" time="0.71">
    <error message="Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host &quot;154.153.170.206&quot;, user &quot;ccyhkvpngqxwcm&quot;, database &quot;d5j2hvlid2h80o&quot;, SSL off" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredTest.java:40)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredTest.java:40)
</error>
  </testcase>
  <testcase name="update_updatesHealthAttribute_true" classname="models.EndangeredTest" time="0.59">
    <error message="Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host &quot;154.153.170.206&quot;, user &quot;ccyhkvpngqxwcm&quot;, database &quot;d5j2hvlid2h80o&quot;, SSL off" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.update_updatesHealthAttribute_true(EndangeredTest.java:49)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "154.153.170.206", user "ccyhkvpngqxwcm", database "d5j2hvlid2h80o", SSL off
	at models.EndangeredTest.update_updatesHealthAttribute_true(EndangeredTest.java:49)
</error>
  </testcase>
</testsuite>